### ISSUE TITLE
Request for New badges Support in Version 2024.8！ Thanks！

### ISSUE THREAD

**Issue by lccox** [Nezz/homeassistant-visionos-theme#6]
Thank you for sharing this project, and the theme you've created is very elegant.！
I'm not sure if you've noticed, but in the HA 2024.8 update, new badges have been introduced. 
Could you possibly add support for these badges? 
Currently, when adding badges to your theme, the background does not become transparent.

Thanks,again!

**Comment by Nezz** [comment]
Hi Iccox! I have fixed the background in Home Assistant:
https://github.com/home-assistant/frontend/pull/21667

The box shadow is also missing, but has been fixed by the HA team:
https://github.com/home-assistant/frontend/issues/21668

I'm not sure when these fixes will be released, but latest 2024.9 will have it.

**Comment by Nezz** [comment]
Support was added in 2024.9. 2024.10 introduced some issues with the new headers, but I'm already working on fixing those.
